force-app/main/default/objects/Account/recordTypes/CustomerAccount.recordType-meta.xml
<RecordType>
    <fullName>CustomerAccount</fullName>
    <active>true</active>
    <description>Patient Account</description>
    <label>Customer Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/SpecialisationAccount.recordType-meta.xml
<RecordType>
    <fullName>SpecialisationAccount</fullName>
    <active>true</active>
    <description>The Clinic Offered Specialisations</description>
    <label>Specialisation Account</label>
</RecordType>

force-app/main/default/objects/Appointments__c/Appointments__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Appointments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointments__c/fields/IsInternal__c.field-meta.xml
<CustomField>
    <fullName>IsInternal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Internal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Patients.recordType-meta.xml
<RecordType>
    <fullName>Patients</fullName>
    <active>true</active>
    <description>Used for Storing Patient Details</description>
    <label>Patients</label>
</RecordType>

force-app/main/default/classes/AppointmentTriggerHandlerTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* All Appointment Trigger Test Logic will be handled in this apex
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Praveen S
* @version        1.0
* @created        2020-11-09
* ──────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
private class AppointmentTriggerHandlerTest {
    
    //Create all test data required
    @testSetup 
    static void setup() {
        
        //Creating Specialization Account
        Id spRectypeId = GenericUtils.getRTIdByRTDevName(Account.sObjectType, 'SpecialisationAccount');
        List<Account> lstAcc = new List<Account>();
        lstAcc.add(GenericTestUtils.createAccount('Cardio', spRectypeId));
        lstAcc.add(GenericTestUtils.createAccount('General', spRectypeId));
        insert lstAcc;
        
        //Enabling Trigger using Trigger Setting
        GenericTestUtils.createTriggerSetting();
        
        //Creating Customer Account(Patients)
        Account objCustomerAcc = GenericTestUtils.createAccount('Test Patient', GenericUtils.getRTIdByRTDevName(Account.sObjectType, 'CustomerAccount'));
        insert objCustomerAcc;
        system.assert(objCustomerAcc.Id != Null, 'Account  Insert Failed');
        
        //Creating Patient Contact
        Contact objpatient = GenericTestUtils.createContact(objCustomerAcc.Id, GenericUtils.getRTIdByRTDevName(Contact.sObjectType, 'Patients'), 'Test', 'Patient', 'tesPatients@bp.com');
        insert objpatient;
        system.assert(objpatient.Id != Null, 'Contact Insert Failed');
        
    }
    
    /**
    * ─────────────────────────────────────────────────────────────────────────────────────────────┐
    * Check if Event Post Queueable is invoked on Appointment creation
    * ──────────────────────────────────────────────────────────────────────────────────────────────
    */
    static TestMethod void onAppointmentInsertTest(){
        
        //Query all Required data
        User  objPortal = [Select Id, RefreshToken__c, Email, ContactId from User where  ContactId != Null AND RefreshToken__c != Null limit 1];
        Contact objpatient = [Select Id from Contact where Email = 'tesPatients@bp.com'];
        
        //Creating Appointment Records
        Appointments__c objAppointment = GenericTestUtils.createAppointment(objPortal.ContactId, objpatient.Id, system.now(), system.now().addHours(1));
        objAppointment.IsInternal__c = true;
        insert objAppointment;
        
        Test.startTest();
        
        //Check if Appointment is inserted 
        system.assert(objAppointment.Id != Null, 'Appointment Insert Failed');
        Map<String,String> headers = new Map<String, String>();
        headers.put('Content-Type','application/json');
        String Body = '{ "access_token": "1/fFAGRNJru1FTz70BzhT3Zg", "expires_in": 3920, "token_type": "Bearer", "scope": "https://www.googleapis.com/auth/drive.metadata.readonly", "refresh_token": "1//xEoDL4iW3cxlI7yDbSRFYNG01kVKM2C-259HOF2aQbI"}{"kind": "calendar#events","etag": ""p32o87il1ijseo0g"","summary": "sampathspraveen@gmail.com",}';
        Test.setMock(HttpCalloutMock.class, new GoogleRestMock(200, 'Success', Body, headers));  
        Test.stopTest();
        
        //Check if Queueable apex is invoked
        List<AsyncApexJob> lstAsync = [SELECT Id, JobItemsProcessed, Status, ApexClassId, ApexClass.Name, JobType FROM AsyncApexJob where ApexClass.Name = 'GoogleInsertEventQueueable'];
        System.assert(lstAsync.size()>0, 'Queueable Apex not invoked.');
        
    }
    
}