force-app/main/default/objects/Appointments__c/Appointments__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Appointments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointments__c/fields/Patients__c.field-meta.xml
<CustomField>
    <fullName>Patients__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patients</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Patients</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointments__c/fields/Physicians__c.field-meta.xml
<CustomField>
    <fullName>Physicians__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Physicians</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Physicians</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Physicians)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__c/TriggerSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to control the Trigger Handling Functionality</description>
    <label>TriggerSetting</label>
</CustomObject>

force-app/main/default/objects/TriggerSetting__c/fields/AppointmentTriggerHandlerAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>AppointmentTriggerHandlerAfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for the functionality around Appointment Trigger Handler</description>
    <label>AppointmentTriggerHandlerAfterInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__c/fields/GoogleCalendarTriggerHandler__c.field-meta.xml
<CustomField>
    <fullName>GoogleCalendarTriggerHandler__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for the functionality around Google Calendar Trigger Handler</description>
    <label>GoogleCalendarTriggerHandler</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__c/fields/UserTriggerHandlerAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>UserTriggerHandlerAfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for the functionality around User Trigger Handler</description>
    <label>UserTriggerHandlerAfterInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GenericTestUtils.cls
@isTest
public class GenericTestUtils {

    public static Account createAccount(String accName, Id recTypeId){
        Account objAcc = new Account();
        objAcc.Name = accName;
        objAcc.RecordtypeId = recTypeId;
        return objAcc;
    }

    public static Contact createContact(Id accId, Id recTypeId, String fName, String lName, String conEmail){
        Contact objCon = new Contact();
        objCon.LastName = lName;
        objCon.FirstName = fName;
        objCon.Email = conEmail;
        objCon.RecordtypeId = recTypeId;
        objCon.AccountId = accId;
        return objCon;
    }

    public static User createPortalUser(Contact objCon, String profileName){

        Profile objProfile = [SELECT Id FROM Profile WHERE Name =: profileName];
        User objUser =  new User(
                                ProfileId = objProfile.Id,
                                FirstName = objCon.FirstName,
                                LastName = objCon.LastName,
                                Email = objCon.Email,
                                Username = objCon.Email,
                                CompanyName = 'TEST',
                                Title = 'title',
                                Alias = 'alias',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                EmailEncodingKey = 'UTF-8',
                                LanguageLocaleKey = 'en_US',
                                LocaleSidKey = 'en_US',
                                IsActive = true,
                                ContactId = objCon.Id
                        );
        return objUser;
    }

    public static User createAdminUser() {
        List<UserRole> roles = [SELECT Id, DeveloperName FROM UserRole Where DeveloperName = 'CEO' Limit 1];
        Profile objProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

        User objUser =  new User(
                                ProfileId = objProfile.Id,
                                FirstName = 'Admin',
                                LastName = 'User',
                                Email = 'sysadmin000@test.com',
                                Username = 'sysadmin000@test.com' + System.currentTimeMillis(),
                                CompanyName = 'TEST',
                                Title = 'title',
                                Alias = 'alias',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                EmailEncodingKey = 'UTF-8',
                                LanguageLocaleKey = 'en_US',
                                UserRoleId = roles.get(0).Id,
                                LocaleSidKey = 'en_US'
                        );
        return objUser;
    }

    public static Appointments__c createAppointment(String docId, String patientId, DateTime startDate, DateTime endDate) {
        Appointments__c objApp = new Appointments__c();
        objApp.Physicians__c = docId;
        objApp.Patients__c = patientId;
        objApp.Subject__c = 'Test Appointment';
        objApp.Start__c = startDate;
        objApp.End__c = endDate;
        return objApp;
    }
    
    public static void createTriggerSetting(){
        TriggerSetting__c setting= new TriggerSetting__c(SetupOwnerId=UserInfo.getOrganizationId(),AppointmentTriggerHandlerAfterInsert__c = true,
                                                        GoogleCalendarTriggerHandler__c = true,UserTriggerHandlerAfterInsert__c = true);
        insert setting;
    }

}